#!/bin/bash

# script: git_instaladores.sh
# autor: Luciano Kalabric <luciano.kalabric@fiocruz.br>
# instituição: Oswaldo Cruz Foundation, Gonçalo Moniz Institute, Bahia, Brazil
# objetivo: uso do git para clonagem e controle de versão dos scripts
# criação: 19 OUT 2021
# ultima atualização: 19 OUT 2021
# atualização: criação deste script para aprender e lembrar os comandos git

# GitHub CLI
# Links: https://docs.github.com/pt/github-cli/github-cli/quickstart
# https://docs.github.com/pt/repositories/creating-and-managing-repositories/cloning-a-repository
# https://www.youtube.com/watch?v=HVsySz-h9r4&t=1402s

# Check version
#git --version

# Set config values
#git config --global user.name "lkalabric"
#git config --global user.email "luciano.kalabric@fiocruz.br"

# Git Help
#git config --help

#
# Option 1 - Initialize a local repo from existing code
#
# cd local-repo-dir
# git init
# ls -la (check .git dir)
# git status (check git status)

# Stop tracking, if desire
# rm -rf .git

# Before first commint
# Ignore files
# touch .gitignore
# nano .gitignore (include files to ignore, one per line)
# git status (check if files were ignored)_

# Add files to staging area
# git add -A or git add .gitignore
# git status

# Remove files from staging area
# git reset file or git reset (remove all files)
# git status

# Our first commit
# git commit -m "Initial commit"
# git log (see commit)

#
# Option 2 - Cloning a remote repo
#

# Clone remote to local (apenas uma vez)
#git clone https://github.com/lkalabric/instaladores.git /home/brazil1/repos/instaladores

# Viewing information about the remote repo
# git remot -v
# git branch -a

# Commit local
#git commit -a -m "Atualização do script assembly.sh."
#git branch -M main

# Push changes to the server
#git push -u origin main

# Git auth
# Username: lkalabric
# Scopes: repo; admin:org; user
# Password=personal token: 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

# Pull changes from server
#git pull
